### ISSUE TITLE
Query param string gets escaped

### ISSUE THREAD

**Issue by andylolz** [israel-fl/Flask-CacheBust#1]
I expect my static filepath to render as:

```
styles.css?q=[hash]
```

Instead, it renders as:

```
styles.css%3Fq%3D[hash]
```

That’s because the question mark and equals get escaped.

**Comment by alexmojaki** [comment]
I'm also having this problem. Did you solve it? Why did you close the PR?

**Comment by andylolz** [comment]
@alexmojaki I think I concluded it probably wouldn’t be merged. PR appears to work, if that’s of any help to you.

**Comment by alexmojaki** [comment]
I think you should reopen the PR, no reason to preemptively close it just because someone doesn't respond. The branch is deleted from github so I can't easily use it.

**Comment by andylolz** [comment]
Kk done.

**Comment by israel-fl** [comment]
Apologies guys, I'm maintaining a few other projects, and have neglected my python repos. I'll review and have this done in the next few days
